### Create expense
POST http://localhost:8080/api/expenses
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{ token }}

{
  "expense_category_id": 2,
  "amount": 50000,
  "note": "Gas",
  "expense_date": 1722330689
}

### Delete expense
DELETE http://localhost:8080/api/expenses/6
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{ token }}

### Update expense
PATCH http://localhost:8080/api/expenses/6
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{ token }}

{
  "expense_category_id": 1,
  "amount": 30000,
  "note": "Makan",
  "expense_date": 1723436107
}

### List expense
GET http://localhost:8080/api/expenses
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{ token }}

### List expense category
GET http://localhost:8080/api/expense-categories
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{ token }}